# Generated by Django 4.1 on 2022-09-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutmeimage_alter_archprojects_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archprojects',
            name='image',
            field=models.ImageField(upload_to='arch_images/'),
        ),
        migrations.AlterField(
            model_name='codingprojects',
            name='image',
            field=models.ImageField(upload_to='coding_images/'),
        ),
    ]
