# Generated by Django 4.1 on 2022-09-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_owner_remove_techskills_person_delete_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='techskills',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.owner'),
        ),
    ]
