# Generated by Django 4.1 on 2022-09-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_techskills_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techskills',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.owner'),
        ),
    ]
