# Generated by Django 4.1 on 2022-10-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_codingimages_archimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='archimages',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='archprojects',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='archprojects',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
